/**
 * Données structurées de l'établissement + textes additionnels de la nouvelle expérience.
 * Les traductions historiques restent dans `constants.ts` (TRANSLATIONS) ; EXTRA est fusionné
 * par-dessus dans LanguageContext (ajouts + corrections de clés manquantes).
 */

import campusHero from '../assets/campus-hero.jpg';

const CDN = 'https://cdn.prod.website-files.com/682f40cedbb46cd6e15b45cb/';

export const SITE = {
  name: 'Georges Claude Private Academy',
  shortName: 'Académie Georges Claude',
  domain: 'https://agc.ma',
  motto: { FR: 'Apprendre avec exigence, réussir avec confiance.', EN: 'Learn with rigour, succeed with confidence.' },
  year: '2026-2027',
  phone: '+212 5233-48010',
  phoneHref: 'tel:+212523348010',
  mobile: '07 08 76 00 34',
  mobileHref: 'tel:+212708760034',
  whatsappHref: 'https://wa.me/212708760034',
  email: 'contact@agc.ma',
  emailAdmissions: 'inscription@agc.ma',
  address: { line1: 'Sidi Bouzid, Route de Casablanca', line2: 'El Jadida 24005, Maroc', plusCode: '6FG2+G8 Sidi Bouzid Centre' },
  mapsUrl: 'https://maps.app.goo.gl/9MoTY1M49wwjcAzQA',
  mapsEmbed: 'https://maps.google.com/maps?q=Acad%C3%A9mie%20Georges%20Claude,%20Sidi%20Bouzid&t=&z=15&ie=UTF8&iwloc=&output=embed',
  social: {
    facebook: 'https://www.facebook.com/AcademieGeorgesClaude',
    instagram: 'https://www.instagram.com/academiegeorgesclaude.officiel/',
  },
  hours: { FR: 'Lun – Ven · 8h00 – 12h00 · pause déjeuner 30 min · 12h30 – 15h30', EN: 'Mon – Fri · 8:00 – 12:00 · 30-min lunch break · 12:30 – 15:30' },
  schedule: { FR: [['8h00 – 12h00', 'Cours du matin'], ['12h00 – 12h30', 'Pause déjeuner'], ['12h30 – 15h30', 'Cours de l’après-midi']], EN: [['8:00 – 12:00', 'Morning classes'], ['12:00 – 12:30', 'Lunch break'], ['12:30 – 15:30', 'Afternoon classes']] },
  director: { name: 'Hugo Ouaddate', role: { FR: 'Directeur Général', EN: 'General Director' } },
  video: 'https://res.cloudinary.com/ddvgp1zrz/video/upload/v1779369814/presentation_q1lmet.mp4',
  cambridgeLogo: 'https://res.cloudinary.com/ddvgp1zrz/image/upload/v1782686752/1042775c-cddc-48a8-89e7-59988c86eabd.png',
};

export const IMG = {
  logo: CDN + '6a064910d98c04735a2b0a6c_aipreview%20logo.png',
  /** Façade de l’école (fichier local, recadré sans le logo) : hero de l’accueil et fond des en-têtes de page */
  school: campusHero,
  schoolCdn: CDN + '69c1d237f890064a67e64342_school.jpg',
  campus: CDN + '6a06427264fc554605941ad3_siteacceuil.jpg',
  classroom: CDN + '69de1b497dac963ec620e39c_Capture%20d%E2%80%99e%CC%81cran%202026-04-14%20a%CC%80%2011.45.22.png',
  kids: CDN + '6a06436b8e9647708e2d4b94_WhatsApp%20Image%202026-03-18%20at%2000.54.42%20(2)%20-%20Copie.jpeg',
  event: CDN + '69c1d233dc4cf99b45616f50_491777598_691096323477848_5143141736472395314_n.jpg',
  director: CDN + '6a0d7414da957cf5a4f9239c_WhatsApp%20Image%202026-05-19%20at%2018.05.08.jpeg',
  signature: CDN + '69de438361b1b716a22c54b2_signaturegen-1776170089424.png',
  eco: CDN + '69de1b48468bdf68fcdab96e_Capture%20d%E2%80%99e%CC%81cran%202026-04-14%20a%CC%80%2011.44.53.png',
  team: CDN + '69cd5b3c8fbdc13183530b9d_team-buid%20(1).jpg',
  canteen: CDN + '6a0641c4501289912ee5bfa9_20260408_102058.jpg',
  library: CDN + '6a06413ec3ed04098d4bd38b_20260408_103650.jpg',
  lab: CDN + '6a0642e35c967a63aaf11e02_20260408_111256.jpg',
  sport: CDN + '6a09f38a9d6e7a93cd71f0cd_WhatsApp%20Image%202026-05-17%20at%2000.58.02%20(1).jpeg',
  cycles: {
    maternelle: CDN + '6a06431c03ee9b32184c769e_20260408_104421%20-%20Copie.jpg',
    primaire: CDN + '6a0642a62888461bc238b590_20260408_105811.jpg',
    college: CDN + '6a06426cebf90414139a75fd_WhatsApp%20Image%202026-04-08%20at%2009.29.14%20(2).jpeg',
    lycee: CDN + '6a0642a45998583a1d309187_%23exames%20%23boncourage.webp',
  },
  cycleGallery: {
    maternelle: [CDN + '6a06432a0dfa1d4698ebf812_20260408_104516%20-%20Copie.jpg', CDN + '6a0643698b957947262c740e_prescolaire4.jpg', CDN + '6a07981a0fca9d4e7566b4fc_WhatsApp%20Image%202026-05-15%20at%2022.53.55.jpeg'],
    primaire: [CDN + '6a0a087f4aa97f21b1f3439e_20260408_105726.jpg', CDN + '6a0a087cf1a88a8406ee24fc_20260408_110706.jpg', CDN + '6a0a087bd8b8ddd9c93c42c1_20260408_105508.jpg'],
    college: [CDN + '6a06426f924d5314fbb6e81b_WhatsApp%20Image%202026-04-08%20at%2009.29.13%20(2).jpeg', CDN + '6a0b4f06dcb3815df08560c6_WhatsApp%20Image%202026-05-18%20at%2018.39.00%20(1).jpeg', CDN + '6a0a1b5cda3ae5e67ecafcec_Capture%20d%E2%80%99e%CC%81cran%202026-05-17%20a%CC%80%2020.49.15.png'],
    lycee: [CDN + '6a0642fb4fb44268106e9ccc_20260408_111637.jpg', CDN + '6a0643d414e10d71b15a3753_20260408_102646.jpg', CDN + '6a0b4f06dcb3815df08560c6_WhatsApp%20Image%202026-05-18%20at%2018.39.00%20(1).jpeg'],
  },
  spaces: [
    CDN + '6a0641da8757c5dc7374be96_20260408_102348.jpg',
    CDN + '6a0642fe5998583a1d309c90_20260408_111431.jpg',
    CDN + '6a064206ed8364d9e0de4b63_20260408_102032.jpg',
    CDN + '6a0641a7335a4fa036c06f69_20260408_112139.avif',
  ],
  activities: [
    CDN + '6a079817dc033d19c3e68bb6_WhatsApp%20Image%202026-05-15%20at%2022.53.52.jpeg',
    CDN + '6a0641a7335a4fa036c06f69_20260408_112139.avif',
    CDN + '6a09f391f71666e4fc4fa209_WhatsApp%20Image%202026-05-17%20at%2000.58.03.jpeg',
    CDN + '6a09f38dd925870ce981901a_WhatsApp%20Image%202026-05-17%20at%2000.58.02.jpeg',
    CDN + '6a09f390456d7c60eaedd730_WhatsApp%20Image%202026-05-17%20at%2000.58.03%20(1).jpeg',
    CDN + '6a09f38a9d6e7a93cd71f0cd_WhatsApp%20Image%202026-05-17%20at%2000.58.02%20(1).jpeg',
    CDN + '6a09f38a9d6e7a93cd71f0cd_WhatsApp%20Image%202026-05-17%20at%2000.58.02%20(1).jpeg',
    CDN + '6a09f39167a0469d6f6065ae_WhatsApp%20Image%202026-05-17%20at%2000.58.03%20(2).jpeg',
  ],
};

export type Lang = 'FR' | 'EN';

/** Textes ajoutés / corrigés. Fusionnés au-dessus de TRANSLATIONS. */
export const EXTRA = {
  FR: {
    common: { middleSchoolCertificate: 'Brevet des Collèges' },
    welcome: {
      text2: "Certification d'excellence académique reconnue par l'État.",
      text3: 'Immersion trilingue dès le plus jeune âge pour un futur sans frontières.',
    },
    nav: {
      contact: 'Contact',
      partners: 'Partenaires',
      recruitment: 'Recrutement',
      menu: 'Menu',
      close: 'Fermer',
      tagline: 'École privée · El Jadida',
      explore: 'Explorer',
      cyclesTitle: 'Les cycles',
    },
    copy: {
      heroTitle: 'À Sidi Bouzid, une école d’excellence, de la maternelle au baccalauréat.',
      heroSub: 'De 3 à 18 ans, une seule école à El Jadida.',
      identityTitle: 'Une école qui tient ses promesses.',
      identityAside: 'Quinze années sous le même toit, avec la même exigence et la même attention.',
      directorTitle: 'Le mot du directeur',
      visionTitle: 'Notre ambition pour chaque élève.',
      videoTitle: 'Deux minutes dans nos couloirs.',
      programsTitle: 'Un parcours, quatre cycles.',
      programsDesc: 'Quatre cycles qui se répondent : chaque étape prépare la suivante, sans rupture ni changement d’école.',
      programsRail: 'De 3 à 18 ans',
      cambridgeTitle: 'Le monde entre en classe.',
      ecoTitle: 'Première école Ruban Vert d’El Jadida.',
      activitiesTitle: 'Après la sonnerie, la vie continue.',
      activitiesDesc: 'Quinze activités chaque semaine pour découvrir un talent, un sport, une passion — et apprendre autrement.',
      lifeTitle: 'Un campus qui donne envie.',
      proofTitle: 'Des résultats qui parlent.',
      journalTitle: 'L’école, semaine après semaine.',
      journalDesc: 'Sorties, projets, résultats, événements : ce que vivent nos élèves, raconté au fil de l’année.',
      practicalTitle: 'Les réponses avant la question.',
      practicalDesc: 'Horaires, transport, homologation, inscription : l’essentiel en un coup d’œil.',
      actionTitle: 'Une place pour votre enfant.',
      actionDesc: 'Trois étapes, un interlocuteur, une réponse sous 48 heures.',
      footerTitle: 'Venez voir l’école.',
      academyTitle: 'Chaque élève peut viser haut.',
      academyLead: 'Depuis sa fondation, l’académie associe exigence académique, bienveillance et ouverture sur le monde — à Sidi Bouzid, aux portes d’El Jadida.',
      programsPageTitle: 'Un chemin sans rupture.',
      cycleTitles: {
        maternelle: 'Les premières années comptent.',
        primaire: 'Lire, écrire, compter, penser.',
        college: 'L’âge des choix.',
        lycee: 'Trois ans pour ouvrir les portes.',
      },
      lifeTitleHero: 'Apprendre aussi entre les cours.',
      newsTitle: 'Ce qui fait vivre l’école.',
      galleryTitle: 'L’année en images.',
      enrollTitle: 'Une place pour votre enfant.',
      enrollLead: 'Quatre étapes simples, un accompagnement personnel du premier appel jusqu’à la rentrée.',
      contactTitle: 'Venez nous rencontrer.',
      recruitTitle: 'Rejoignez l’équipe.',
      partnersTitle: 'Des partenaires qui ouvrent le monde.',
      spaceChapter: 'Nos espaces',
      cambridgeStandard: 'Un standard mondial.',
      enrollFormTitle: 'Deux minutes suffisent.',
      recruitJobs: 'Les talents que nous cherchons.',
      lifeMoments: 'Vivez l’expérience.',
    },
    ui: {
      readMore: 'Lire',
      viewAll: 'Tout voir',
      seePrograms: 'Voir les programmes',
      discoverAcademy: "Découvrir l'académie",
      enroll: "S'inscrire pour 2026-2027",
      enrollShort: "S'inscrire",
      call: 'Appeler',
      writeUs: 'Nous écrire',
      whatsapp: 'WhatsApp',
      openMaps: 'Ouvrir dans Google Maps',
      hours: 'Horaires',
      address: 'Adresse',
      phone: 'Téléphone',
      email: 'Email',
      followUs: 'Suivez-nous',
      scroll: 'Défiler',
      chapter: 'Chapitre',
      backHome: "Retour à l'accueil",
      notFound: 'Cette page n’existe pas.',
      notFoundDesc: 'Le lien est peut-être ancien. Retrouvez ce que vous cherchez depuis l’accueil ou contactez-nous.',
      loading: 'Chargement',
      requiredNote: 'Champs obligatoires',
      sending: 'Envoi…',
      sentTitle: 'Message envoyé',
      sentDesc: 'Merci. Notre équipe vous répond sous 48 heures ouvrées.',
      newMessage: 'Envoyer un autre message',
      videoTitle: 'Une journée à l’académie',
      videoDesc: 'Deux minutes pour ressentir l’ambiance de nos classes, de nos terrains et de nos couloirs.',
      keyFacts: 'Repères',
      trustTitle: 'Ce qui fonde la confiance',
      results: 'Résultats',
      resultsYear: 'Année scolaire 2025-2026',
      mentions: 'Mentions très bien',
      mentionsDesc: 'Nos lauréats du baccalauréat 2025-2026',
      mentionsLine: 'Nos lauréats 2025-2026 ont décroché le baccalauréat avec des mentions très bien.',
      success100: 'de réussite',
      success100Desc: 'Baccalauréat et Brevet (BEM)',
      maxClass: 'élèves maximum',
      maxClassDesc: 'par classe, pour un suivi réel',
      activitiesCount: 'activités',
      activitiesDesc: 'parascolaires chaque semaine',
      ecoFirst: 'école Ruban Vert',
      ecoFirstDesc: 'première d’El Jadida labellisée',
      cambridgeFacts: 'Programme Cambridge',
      cambridgeDesc: 'intégration progressive, certifications reconnues',
      practicalTitle: 'Informations pratiques',
      practicalDesc: 'Les réponses que les familles nous demandent le plus souvent.',
      moreQuestions: 'Une autre question ?',
      moreQuestionsDesc: 'Écrivez-nous ou appelez le secrétariat, nous répondons personnellement.',
      lifeTeaser: 'Un campus pensé pour grandir',
      lifeTeaserDesc: 'Terrains, laboratoires, médiathèque, cantine : découvrez l’environnement quotidien de nos élèves.',
      journalTitle: 'Le journal de l’académie',
      journalDesc: 'Sorties, projets, résultats et événements : la vie de l’école, semaine après semaine.',
      journalEmpty: 'Les prochaines actualités arrivent bientôt.',
      programsTitle: 'Un seul parcours, quatre cycles',
      programsDesc: 'De la première rentrée en maternelle au baccalauréat, chaque étape prépare la suivante.',
      dragHint: 'Faites défiler',
      spacesLink: 'Voir l’espace',
      requirementsTitle: 'Le dossier d’inscription',
      requirementsDesc: 'À réunir pour finaliser l’admission après l’entretien et le test de niveau.',
      stepsTitle: 'Quatre étapes, un accompagnement',
      contactTitle: 'Venez nous rencontrer',
      contactDesc: 'Une visite du campus vaut mieux qu’un long discours. Nous vous accueillons sur rendez-vous, du lundi au vendredi.',
      contactFormTitle: 'Demande d’informations',
      contactFormDesc: 'Laissez-nous vos coordonnées, nous vous rappelons.',
      subject: 'Objet',
      subjectOptions: ['Inscription 2026-2027', 'Visite du campus', 'Transport scolaire', 'Autre question'],
      message: 'Message',
      send: 'Envoyer',
      partnersIntro: 'Des collaborations choisies pour élargir l’horizon de nos élèves.',
      spaceBack: 'Retour à la vie scolaire',
      spaceOthers: 'Autres espaces',
      galleryEmpty: 'La galerie se remplit au fil de l’année.',
      allSpaces: 'Nos espaces',
      eventDetails: 'Détails de l’événement',
      share: 'Partager',
      copied: 'Lien copié',
      related: 'À lire aussi',
      backNews: 'Toutes les actualités',
      jobsTitle: 'Postes ouverts',
      jobsEmpty: 'Aucun poste ouvert pour le moment. Envoyez-nous une candidature spontanée.',
      spontaneous: 'Candidature spontanée',
      applyFor: 'Postuler',
      whyJoin: 'Pourquoi nous rejoindre',
      cvLabel: 'CV (PDF)',
      clLabel: 'Lettre de motivation (PDF)',
      subjectTaught: 'Matière enseignée',
      firstName: 'Prénom',
      lastName: 'Nom',
      choosePosition: 'Choisissez un poste ou une candidature spontanée pour continuer.',
      cycleFor: 'Pour les',
      cycleAges: { maternelle: '3 – 5 ans', primaire: '6 – 11 ans', college: '12 – 14 ans', lycee: '15 – 18 ans' },
      nextCycle: 'Cycle suivant',
      prevCycle: 'Cycle précédent',
      dayTitle: 'Une journée type',
      program: 'Le programme',
      pillars: 'Ce que nous cultivons',
      admissionsPageTitle: 'Rejoindre l’académie',
      timelineTitle: 'Notre histoire',
      teamTitle: 'L’équipe de direction',
    },
  },
  EN: {
    common: { middleSchoolCertificate: 'Middle School Certificate' },
    nav: {
      contact: 'Contact',
      partners: 'Partners',
      recruitment: 'Careers',
      menu: 'Menu',
      close: 'Close',
      tagline: 'Private school · El Jadida',
      explore: 'Explore',
      cyclesTitle: 'The cycles',
    },
    copy: {
      heroTitle: 'In Sidi Bouzid, a school of excellence, from preschool to the baccalaureate.',
      heroSub: 'From 3 to 18, one school in El Jadida.',
      identityTitle: 'A school that keeps its promises.',
      identityAside: 'Fifteen years under one roof, with the same standards and the same care.',
      directorTitle: 'A word from the director',
      visionTitle: 'Our ambition for every student.',
      videoTitle: 'Two minutes in our corridors.',
      programsTitle: 'One path, four cycles.',
      programsDesc: 'Four cycles that build on each other: every stage prepares the next, with no break and no change of school.',
      programsRail: 'From age 3 to 18',
      cambridgeTitle: 'The world comes into class.',
      ecoTitle: 'El Jadida’s first Green Ribbon school.',
      activitiesTitle: 'After the bell, life goes on.',
      activitiesDesc: 'Fifteen activities every week to discover a talent, a sport, a passion — and learn differently.',
      lifeTitle: 'A campus that inspires.',
      proofTitle: 'Results that speak for themselves.',
      journalTitle: 'The school, week after week.',
      journalDesc: 'Outings, projects, results, events: what our students experience, told throughout the year.',
      practicalTitle: 'Answers before the question.',
      practicalDesc: 'Hours, transport, accreditation, enrolment: the essentials at a glance.',
      actionTitle: 'A place for your child.',
      actionDesc: 'Three steps, one contact person, an answer within 48 hours.',
      footerTitle: 'Come and see the school.',
      academyTitle: 'Every student can aim high.',
      academyLead: 'Since its founding, the academy has combined academic rigour, care and openness to the world — in Sidi Bouzid, at the gates of El Jadida.',
      programsPageTitle: 'One unbroken path.',
      cycleTitles: {
        maternelle: 'The first years count.',
        primaire: 'Read, write, count, think.',
        college: 'The age of choices.',
        lycee: 'Three years to open doors.',
      },
      lifeTitleHero: 'Learning between classes too.',
      newsTitle: 'What brings the school to life.',
      galleryTitle: 'The year in pictures.',
      enrollTitle: 'A place for your child.',
      enrollLead: 'Four simple steps, personal guidance from the first call to the first day of school.',
      contactTitle: 'Come and meet us.',
      recruitTitle: 'Join the team.',
      partnersTitle: 'Partners who open the world.',
      spaceChapter: 'Our spaces',
      cambridgeStandard: 'A global standard.',
      enrollFormTitle: 'Two minutes is enough.',
      recruitJobs: 'The talent we are looking for.',
      lifeMoments: 'Live the experience.',
    },
    ui: {
      readMore: 'Read',
      viewAll: 'View all',
      seePrograms: 'See the programs',
      discoverAcademy: 'Discover the academy',
      enroll: 'Enrol for 2026-2027',
      enrollShort: 'Enrol',
      call: 'Call',
      writeUs: 'Write to us',
      whatsapp: 'WhatsApp',
      openMaps: 'Open in Google Maps',
      hours: 'Hours',
      address: 'Address',
      phone: 'Phone',
      email: 'Email',
      followUs: 'Follow us',
      scroll: 'Scroll',
      chapter: 'Chapter',
      backHome: 'Back to home',
      notFound: 'This page does not exist.',
      notFoundDesc: 'The link may be outdated. Find what you need from the home page or contact us.',
      loading: 'Loading',
      requiredNote: 'Required fields',
      sending: 'Sending…',
      sentTitle: 'Message sent',
      sentDesc: 'Thank you. Our team replies within 48 working hours.',
      newMessage: 'Send another message',
      videoTitle: 'A day at the academy',
      videoDesc: 'Two minutes to feel the atmosphere of our classrooms, fields and corridors.',
      keyFacts: 'Key facts',
      trustTitle: 'What builds trust',
      results: 'Results',
      resultsYear: 'School year 2025-2026',
      mentions: 'Highest honours',
      mentionsDesc: 'Our 2025-2026 baccalaureate graduates',
      mentionsLine: 'Our 2025-2026 graduates passed the baccalaureate with the highest honours.',
      success100: 'success rate',
      success100Desc: 'Baccalaureate and middle-school certificate',
      maxClass: 'students maximum',
      maxClassDesc: 'per class, for real follow-up',
      activitiesCount: 'activities',
      activitiesDesc: 'extracurricular, every week',
      ecoFirst: 'Green Ribbon school',
      ecoFirstDesc: 'the first certified in El Jadida',
      cambridgeFacts: 'Cambridge programme',
      cambridgeDesc: 'progressive integration, recognised certifications',
      practicalTitle: 'Practical information',
      practicalDesc: 'The answers families ask us for most often.',
      moreQuestions: 'Another question?',
      moreQuestionsDesc: 'Write or call the office, we answer personally.',
      lifeTeaser: 'A campus designed for growing',
      lifeTeaserDesc: 'Fields, laboratories, media library, canteen: discover our students’ daily environment.',
      journalTitle: 'The academy journal',
      journalDesc: 'Outings, projects, results and events: school life, week after week.',
      journalEmpty: 'The next news is coming soon.',
      programsTitle: 'One path, four cycles',
      programsDesc: 'From the first day of preschool to the baccalaureate, each stage prepares the next.',
      dragHint: 'Scroll',
      spacesLink: 'See the space',
      requirementsTitle: 'The enrolment file',
      requirementsDesc: 'To gather in order to finalise admission after the interview and placement test.',
      stepsTitle: 'Four steps, one guidance',
      contactTitle: 'Come and meet us',
      contactDesc: 'A campus visit is worth more than a long speech. We welcome you by appointment, Monday to Friday.',
      contactFormTitle: 'Information request',
      contactFormDesc: 'Leave your details, we will call you back.',
      subject: 'Subject',
      subjectOptions: ['Enrolment 2026-2027', 'Campus visit', 'School transport', 'Other question'],
      message: 'Message',
      send: 'Send',
      partnersIntro: 'Chosen collaborations to broaden our students’ horizons.',
      spaceBack: 'Back to school life',
      spaceOthers: 'Other spaces',
      galleryEmpty: 'The gallery fills up throughout the year.',
      allSpaces: 'Our spaces',
      eventDetails: 'Event details',
      share: 'Share',
      copied: 'Link copied',
      related: 'Also read',
      backNews: 'All news',
      jobsTitle: 'Open positions',
      jobsEmpty: 'No open position at the moment. Send us a spontaneous application.',
      spontaneous: 'Spontaneous application',
      applyFor: 'Apply',
      whyJoin: 'Why join us',
      cvLabel: 'CV (PDF)',
      clLabel: 'Cover letter (PDF)',
      subjectTaught: 'Subject taught',
      firstName: 'First name',
      lastName: 'Last name',
      choosePosition: 'Choose a position or a spontaneous application to continue.',
      cycleFor: 'For ages',
      cycleAges: { maternelle: '3 – 5', primaire: '6 – 11', college: '12 – 14', lycee: '15 – 18' },
      nextCycle: 'Next cycle',
      prevCycle: 'Previous cycle',
      dayTitle: 'A typical day',
      program: 'The programme',
      pillars: 'What we cultivate',
      admissionsPageTitle: 'Joining the academy',
      timelineTitle: 'Our story',
      teamTitle: 'The leadership team',
    },
  },
};

/** Pièces du dossier d'inscription (réintégrées depuis l'ancienne page Admissions non routée). */
export const REQUIREMENTS = {
  FR: [
    "Formulaire d'inscription dûment rempli",
    "Copie de l'acte de naissance",
    'Bulletins scolaires des deux dernières années',
    "Certificat de scolarité de l'établissement précédent",
    "4 photos d'identité récentes",
    "Copie de la carte d'identité des parents",
  ],
  EN: [
    'Completed enrolment form',
    'Copy of the birth certificate',
    'School reports for the last two years',
    'School attendance certificate from the previous school',
    '4 recent ID photos',
    "Copy of the parents' ID card",
  ],
};

/** Fiches infrastructures (anciennes pages /spaces/*, désormais reliées depuis Vie scolaire). */
export interface SpaceInfo { slug: string; title: Record<Lang, string>; intro: Record<Lang, string>; image: string; features: Record<Lang, [string, string][]> }

export const SPACES: Record<'sports' | 'labs' | 'library', SpaceInfo> = {
  sports: {
    slug: 'sports',
    title: { FR: 'Infrastructures sportives', EN: 'Sports facilities' },
    intro: {
      FR: 'Le sport est au cœur de notre projet pédagogique. Nos installations permettent la pratique de plus de 15 disciplines dans des conditions professionnelles.',
      EN: 'Sport is at the heart of our educational project. Our facilities allow more than 15 disciplines to be practised in professional conditions.',
    },
    image: IMG.sport,
    features: {
      FR: [
        ['Piscine semi-olympique', 'Bassin de 25 m chauffé, filtration à l’ozone.'],
        ['Terrain de football synthétique', 'Gazon de dernière génération homologué FIFA.'],
        ['Gymnase omnisports', 'Parquet en chêne massif : basket, volley, hand.'],
        ['Salle de fitness', 'Équipements cardio et musculation connectés.'],
      ],
      EN: [
        ['Semi-Olympic pool', '25 m heated pool with ozone filtration.'],
        ['Synthetic football pitch', 'Latest-generation FIFA-approved turf.'],
        ['Multi-sport gymnasium', 'Solid oak floor: basketball, volleyball, handball.'],
        ['Fitness room', 'Connected cardio and strength equipment.'],
      ],
    },
  },
  labs: {
    slug: 'labs',
    title: { FR: 'Laboratoires de sciences', EN: 'Science laboratories' },
    intro: {
      FR: 'Physique, chimie, SVT et robotique (drones, impression 3D, robots) : des espaces équipés pour expérimenter, mesurer, se tromper et recommencer.',
      EN: 'Physics, chemistry, life sciences and robotics (drones, 3D printing, robots): equipped spaces to experiment, measure, fail and try again.',
    },
    image: IMG.lab,
    features: {
      FR: [
        ['Labo de physique', 'Bancs d’optique, kits d’électronique et capteurs numériques.'],
        ['Labo de chimie', 'Hottes aspirantes, verrerie de précision et réactifs sécurisés.'],
        ['Labo de SVT', 'Microscopes binoculaires et modèles anatomiques 3D.'],
        ['Espace robotique', 'Drones, imprimantes 3D, robots programmables et kits Arduino / LEGO.'],
      ],
      EN: [
        ['Physics lab', 'Optical benches, electronics kits and digital sensors.'],
        ['Chemistry lab', 'Fume hoods, precision glassware and secured reagents.'],
        ['Life sciences lab', 'Binocular microscopes and 3D anatomical models.'],
        ['Robotics space', 'Drones, 3D printers, programmable robots and Arduino / LEGO kits.'],
      ],
    },
  },
  library: {
    slug: 'library',
    title: { FR: 'Médiathèque & bibliothèque', EN: 'Media centre & library' },
    intro: {
      FR: 'Un lieu calme pour lire, chercher et travailler ensemble, avec un fonds trilingue et des ressources numériques.',
      EN: 'A quiet place to read, research and work together, with a trilingual collection and digital resources.',
    },
    image: IMG.library,
    features: {
      FR: [
        ['Fonds documentaire', 'Plus de 15 000 ouvrages en français, anglais et arabe.'],
        ['Espace numérique', 'Tablettes et ordinateurs avec accès aux bases de données.'],
        ['Zone de lecture', 'Fauteuils ergonomiques, ambiance propice à la concentration.'],
        ['Salle de travail', 'Espaces modulables pour les projets de groupe.'],
      ],
      EN: [
        ['Collection', 'More than 15,000 books in French, English and Arabic.'],
        ['Digital space', 'Tablets and computers with database access.'],
        ['Reading area', 'Ergonomic armchairs, an atmosphere for concentration.'],
        ['Work room', 'Modular spaces for group projects.'],
      ],
    },
  },
};

export type SpaceSlug = keyof typeof SPACES;


/** Poursuite d'études : les grandes filières marocaines auxquelles l'académie prépare ses bacheliers. */
export const AFTER_BAC = {
  FR: {
    chapter: 'Et après le bac ?',
    title: 'Préparés pour les grandes filières du Maroc.',
    lead: 'Nos élèves arrivent en terminale avec des bases solides, trois langues et une méthode de travail. Dès la première, nous les préparons aux concours et aux dossiers d’admission des filières les plus sélectives du pays.',
    note: 'Orientation personnalisée, préparation aux concours, entraînement aux entretiens et accompagnement post-bac.',
    families: [
      { name: 'Classes préparatoires (CPGE)', desc: 'Filières scientifiques, économiques et commerciales vers les grandes écoles.', items: ['MPSI / MP', 'PCSI / PSI', 'ECS / ECT', 'TSI'] },
      { name: 'Écoles d’ingénieurs', desc: 'Les grandes écoles publiques d’ingénierie du Royaume.', items: ['EMI', 'ENSA', 'ENSAM', 'INPT', 'ENSIAS', 'EHTP', 'ENSEM', 'IAV Hassan II'] },
      { name: 'Santé', desc: 'Facultés de médecine, pharmacie et médecine dentaire.', items: ['Médecine', 'Pharmacie', 'Médecine dentaire', 'UM6SS'] },
      { name: 'Commerce & gestion', desc: 'Les écoles de management de référence.', items: ['ENCG', 'ISCAE', 'HEM', 'ESCA'] },
      { name: 'Universités d’excellence', desc: 'Programmes universitaires sélectifs, en anglais ou en français.', items: ['UM6P', 'Al Akhawayn', 'UIR', 'ENA (Architecture)'] },
    ],
  },
  EN: {
    chapter: 'And after the baccalaureate?',
    title: 'Prepared for Morocco’s top programmes.',
    lead: 'Our students reach their final year with solid foundations, three languages and a working method. From the penultimate year, we prepare them for the entrance exams and admission files of the country’s most selective programmes.',
    note: 'Personal guidance, exam preparation, interview training and post-baccalaureate support.',
    families: [
      { name: 'Preparatory classes (CPGE)', desc: 'Scientific, economic and business tracks towards the grandes écoles.', items: ['MPSI / MP', 'PCSI / PSI', 'ECS / ECT', 'TSI'] },
      { name: 'Engineering schools', desc: 'The Kingdom’s leading public engineering schools.', items: ['EMI', 'ENSA', 'ENSAM', 'INPT', 'ENSIAS', 'EHTP', 'ENSEM', 'IAV Hassan II'] },
      { name: 'Health', desc: 'Faculties of medicine, pharmacy and dentistry.', items: ['Medicine', 'Pharmacy', 'Dentistry', 'UM6SS'] },
      { name: 'Business & management', desc: 'The reference management schools.', items: ['ENCG', 'ISCAE', 'HEM', 'ESCA'] },
      { name: 'Universities of excellence', desc: 'Selective university programmes, in English or French.', items: ['UM6P', 'Al Akhawayn', 'UIR', 'ENA (Architecture)'] },
    ],
  },
};

/** Les trois sections de la maternelle. */
export const MATERNELLE_SECTIONS = {
  FR: {
    chapter: 'Les trois sections',
    title: 'Trois années pour bien commencer.',
    lead: 'Chaque section a son rythme et ses objectifs. L’enfant progresse à son pas, dans la même école, avec des enseignantes qui le connaissent.',
    items: [
      { short: 'PS', name: 'Petite Section', ages: '3 – 4 ans', desc: 'La première rentrée : se séparer en douceur, découvrir la classe, les autres et le plaisir d’apprendre.', points: ['Accueil et rituels rassurants', 'Langage et vocabulaire au quotidien', 'Motricité, jeux et manipulation', 'Premières comptines en français et en anglais'] },
      { short: 'MS', name: 'Moyenne Section', ages: '4 – 5 ans', desc: 'L’année de l’autonomie : parler, écouter, se concentrer, coopérer et commencer à tracer.', points: ['Graphisme et préparation à l’écriture', 'Premiers nombres et formes', 'Immersion en anglais et arabe', 'Éveil scientifique et artistique'] },
      { short: 'GS', name: 'Grande Section', ages: '5 – 6 ans', desc: 'La passerelle vers le primaire : lire ses premiers mots, compter, raisonner et gagner en confiance.', points: ['Conscience phonologique et lecture', 'Écriture cursive et nombres jusqu’à 30', 'Trilinguisme structuré', 'Projets de classe et responsabilités'] },
    ],
  },
  EN: {
    chapter: 'The three sections',
    title: 'Three years to start well.',
    lead: 'Each section has its own rhythm and goals. Children progress at their own pace, in the same school, with teachers who know them.',
    items: [
      { short: 'PS', name: 'Petite Section', ages: '3 – 4', desc: 'The first school year: separating gently, discovering the classroom, others and the joy of learning.', points: ['Reassuring welcome and rituals', 'Everyday language and vocabulary', 'Motor skills, play and handling', 'First rhymes in French and English'] },
      { short: 'MS', name: 'Moyenne Section', ages: '4 – 5', desc: 'The year of autonomy: speaking, listening, focusing, cooperating and starting to trace.', points: ['Pre-writing and graphic skills', 'First numbers and shapes', 'English and Arabic immersion', 'Science and art discovery'] },
      { short: 'GS', name: 'Grande Section', ages: '5 – 6', desc: 'The bridge to primary school: reading first words, counting, reasoning and building confidence.', points: ['Phonological awareness and reading', 'Cursive writing and numbers to 30', 'Structured trilingualism', 'Class projects and responsibilities'] },
    ],
  },
};
